### ISSUE TITLE
Change supersaturation definition

### ISSUE THREAD

**Issue by trontrytel** [CliMA/Thermodynamics.jl#154]
I would like to change our supersaturation definition. What we currently have is: `S = q_vap / q_sat - 1`

`S` is typically defined as a ratio of partial pressures `p_vap / p_vap_sat - 1`. The outcome will be close, but not exactly the same.

It should not affect the `Thermodynamics` package because we don't use `S` to compute anything internally. But I would like to use it in `CloudMicrophysics` in some of the ice nucleation parameterizations

cc: @tapios, @amylu00, @szy21

**Comment by szy21** [comment]
Sounds good, I didn't know these two are different...

**Comment by tapios** [comment]
Sounds good to me.
