### ISSUE TITLE
Why is density an input to `virtual_temperature`?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Thermodynamics.jl#190]
It's an input:

https://github.com/CliMA/Thermodynamics.jl/blob/20de40f66170bca8deeff394c1880dd0559a27b7/src/relations.jl#L2579

but is not used:

https://github.com/CliMA/Thermodynamics.jl/blob/20de40f66170bca8deeff394c1880dd0559a27b7/src/relations.jl#L2582-L2583

**Comment by charleskawczynski** [comment]
This is a mistake, we can remove it.
