### ISSUE TITLE
Remove Artifacts.toml

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/Thermodynamics.jl#214]
Is this artifact file used?

https://github.com/CliMA/Thermodynamics.jl/blob/163e124241d7fe3927a1adc9d1db1359cc131ecf/test/Artifacts.toml#L1-L2

**Comment by charleskawczynski** [comment]
Ah, no! I managed to remove the dependence on artifacts in the test suite 🙂. We can remove that file.
